version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_face_attendance_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/smart_attendance_db
      - JWT_SECRET=production_docker_compose_jwt_secret_token_2026
      - JWT_EXPIRES_IN=24h
      - TIMEZONE=Asia/Kolkata
      - CLIENT_URL=http://localhost:5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: smart_face_attendance_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
